# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: smarter-menu-serverless
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

custom:
  iamName:
    dev: 'smarter-menu-lambda-role-dev'
    prod: 'smarter-menu-lambda-role-prod'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-central-1
  deploymentBucket:
    blockPublicAccess: true
    skipPolicySetup: true
  httpApi:
    cors:
      allowedOrigins:
        - https://www.smarter-menu.de
      allowedHeaders:
        - x-netlify-host
        - content-type

  iam:
    role:
      name: 'smarter-menu-lambda-role-prod'
      statements:
        - Effect: 'Allow'
          Resource: '*'
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:DeleteItem

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  hello:
    handler: functions/hello.handler
    memorySize: 128
    events:
      - httpApi:
          path: /hello
          method: post
  get-categories:
    handler: functions/get-categories.handler
    memorySize: 512
    events:
      - httpApi:
          path: /categories
          method: post
  get-items:
    handler: functions/get-items.handler
    memorySize: 512
    events:
      - httpApi:
          path: /items
          method: post
  get-items-meta:
    handler: functions/get-items-meta.handler
    memorySize: 512
    events:
      - httpApi:
          path: /items-meta
          method: post
  get-page-configs:
    handler: functions/get-page-configs.handler
    memorySize: 512
    events:
      - httpApi:
          path: /page-configs
          method: post
  login:
    handler: functions/login.handler
    memorySize: 512
    events:
      - httpApi:
          path: /login
          method: post
  get-all-for-customer:
    handler: functions/get-all-for-customer.handler
    memorySize: 512
    events:
      - httpApi:
          path: /customer-data
          method: post
  update-document:
    handler: functions/update-document.handler
    memorySize: 512
    events:
      - httpApi:
          path: /update
          method: post
