# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: smarter-menu-serverless
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-central-1
  deploymentBucket:
    blockPublicAccess: true
    skipPolicySetup: true
  iam:
    role:
      name: 'smarter-menu-lambda-role'
      statements:
        - Effect: 'Allow'
          Resource: '*'
          Action:
            - dynamodb:Query
            - dynamodb:GetItem

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  hello:
    handler: functions/hello.handler
    events:
      - httpApi:
          path: /hello
          method: post
  get-categories:
    handler: functions/get-categories.handler
    events:
      - httpApi:
          path: /categories
          method: post
  get-items:
    handler: functions/get-items.handler
    events:
      - httpApi:
          path: /items
          method: post
  get-items-meta:
    handler: functions/get-items-meta.handler
    events:
      - httpApi:
          path: /items-meta
          method: post
  get-page-config:
    handler: functions/get-page-config.handler
    events:
      - httpApi:
          path: /page-config
          method: post
